package com.sweak.qralarm.features.emergency.settings.util

val EMERGENCY_AVAILABLE_SLIDER_RANGES = listOf(0..50, 0..75, 0..100)
val EMERGENCY_DEFAULT_SLIDER_RANGE = 0..100
val EMERGENCY_AVAILABLE_REQUIRED_MATCHES = listOf(10, 25, 50, 75, 100)
const val EMERGENCY_DEFAULT_REQUIRED_MATCHES = 50