package com.sweak.qralarm.core.domain.alarm

val AVAILABLE_SNOOZE_NUMBERS = listOf(0, 1, 2, 3)
val AVAILABLE_SNOOZE_DURATIONS_IN_MINUTES = listOf(2, 3, 5, 10, 15, 20)

val AVAILABLE_GENTLE_WAKE_UP_DURATIONS_IN_SECONDS = listOf(60, 30, 10 ,0)
val AVAILABLE_TEMPORARY_MUTE_DURATIONS_IN_SECONDS = listOf(45, 30, 15, 0)