package com.sweak.qralarm.alarm

const val ALARM_NOTIFICATION_CHANNEL_ID = "QRAlarmNotificationChannelId"
const val ALARM_SET_INDICATION_NOTIFICATION_CHANNEL_ID = "QRAlarmSetIndicationNotificationChannelId"

const val ALARM_MISSED_NOTIFICATION_REQUEST_CODE = 100
const val ALARM_MISSED_NOTIFICATION_ID = 101

const val UPCOMING_ALARM_NOTIFICATION_REQUEST_CODE = 102